### ISSUE TITLE
PermissionError raised after --help

### ISSUE THREAD

**Issue by tomschr** [liangxin1300/cluster_preflight_check#6]
## Problem

When calling `cluster-preflight-check --help` as an ordinary user, I get the following traceback:

```
$ python3 -m venv .env
$ . .env/bin/activate
$ pip install cluster-preflight-check
$ cluster-preflight-check --help
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File
"/tmp/toms/preflight/.env/lib64/python3.6/site-packages/cluster_preflight_check/main.py",
line 376, in run setup_logging(context) File
"/tmp/toms/preflight/.env/lib64/python3.6/site-packages/cluster_preflight_check/main.py",
line 354, in setup_logging file_handler =
logging.FileHandler(context.logfile) File
"/usr/lib64/python3.6/logging/__init__.py", line 1030, in __init__
StreamHandler.__init__(self, self._open()) File
"/usr/lib64/python3.6/logging/__init__.py", line 1059, in _open return
open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied:
'/var/log/cluster-preflight-check.log' (.env)
toms@edison:/tmp/toms/preflight> cluster-preflight-check --help
Traceback (most recent call last): File "<string>", line 5, in <module>
File
"/tmp/toms/preflight/.env/lib64/python3.6/site-packages/cluster_preflight_check/main.py",
line 376, in run setup_logging(context) File
"/tmp/toms/preflight/.env/lib64/python3.6/site-packages/cluster_preflight_check/main.py",
line 354, in setup_logging file_handler =
logging.FileHandler(context.logfile) File
"/usr/lib64/python3.6/logging/__init__.py", line 1030, in __init__
StreamHandler.__init__(self, self._open()) File
"/usr/lib64/python3.6/logging/__init__.py", line 1059, in _open return
open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied:
'/var/log/cluster-preflight-check.log'
```

## Expected Solution

Normal users should be able to use `--help` to get an overview of all possible options etc.

**Comment by tomschr** [comment]
Please, don't use #8 as a fix for this issue. IMHO it's not. :-) A user -- regardless of root or any other -- should always get an output when using `--help` and not an error message.
